///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Bakalarka.Vue.Laracasts
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Laracasts_log_main_stats recording.
    /// </summary>
    [TestModule("efbdccc3-fd7a-4e84-824d-b25614e2a4d3", ModuleType.Recording, 1)]
    public partial class Laracasts_log_main_stats : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Bakalarka.BakalarkaRepository repository.
        /// </summary>
        public static global::Bakalarka.BakalarkaRepository repo = global::Bakalarka.BakalarkaRepository.Instance;

        static Laracasts_log_main_stats instance = new Laracasts_log_main_stats();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Laracasts_log_main_stats()
        {
            FWSeries = "";
            FWVideos = "";
            LanguageSeries = "";
            LanguagesVideos = "";
            TechniquesSeries = "";
            TechniquesVideos = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Laracasts_log_main_stats Instance
        {
            get { return instance; }
        }

#region Variables

        string _FWSeries;

        /// <summary>
        /// Gets or sets the value of variable FWSeries.
        /// </summary>
        [TestVariable("f04dabda-9f6c-4fa5-b881-63819532c2a1")]
        public string FWSeries
        {
            get { return _FWSeries; }
            set { _FWSeries = value; }
        }

        string _FWVideos;

        /// <summary>
        /// Gets or sets the value of variable FWVideos.
        /// </summary>
        [TestVariable("b1e88d66-ce52-400a-99be-a61fe440c003")]
        public string FWVideos
        {
            get { return _FWVideos; }
            set { _FWVideos = value; }
        }

        string _LanguageSeries;

        /// <summary>
        /// Gets or sets the value of variable LanguageSeries.
        /// </summary>
        [TestVariable("1f68c32d-323b-4dd2-8ef3-fbb8b4a95e50")]
        public string LanguageSeries
        {
            get { return _LanguageSeries; }
            set { _LanguageSeries = value; }
        }

        string _LanguagesVideos;

        /// <summary>
        /// Gets or sets the value of variable LanguagesVideos.
        /// </summary>
        [TestVariable("4bddc2a2-8333-4658-a03d-c1b695f4f6ad")]
        public string LanguagesVideos
        {
            get { return _LanguagesVideos; }
            set { _LanguagesVideos = value; }
        }

        string _TechniquesSeries;

        /// <summary>
        /// Gets or sets the value of variable TechniquesSeries.
        /// </summary>
        [TestVariable("b6de5a96-d897-4465-a4be-74af0def2675")]
        public string TechniquesSeries
        {
            get { return _TechniquesSeries; }
            set { _TechniquesSeries = value; }
        }

        string _TechniquesVideos;

        /// <summary>
        /// Gets or sets the value of variable TechniquesVideos.
        /// </summary>
        [TestVariable("37308f6d-f1fd-4318-b982-4d47754a83ce")]
        public string TechniquesVideos
        {
            get { return _TechniquesVideos; }
            set { _TechniquesVideos = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // FW
            Report.Log(ReportLevel.Info, "Section", "FW", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Title' from item 'Laracasts.Manual.FWSerNumber' and assigning its value to variable 'FWSeries'.", repo.Laracasts.Manual.FWSerNumberInfo, new RecordItemIndex(1));
            FWSeries = repo.Laracasts.Manual.FWSerNumber.Element.GetAttributeValueText("Title");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", FWSeries, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Title' from item 'Laracasts.Manual.FWVidNumber' and assigning its value to variable 'FWVideos'.", repo.Laracasts.Manual.FWVidNumberInfo, new RecordItemIndex(3));
            FWVideos = repo.Laracasts.Manual.FWVidNumber.Element.GetAttributeValueText("Title");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", FWVideos, new RecordItemIndex(4));
            
            // Languages
            Report.Log(ReportLevel.Info, "Section", "Languages", new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Title' from item 'Laracasts.Manual.LangSerNumber' and assigning its value to variable 'LanguageSeries'.", repo.Laracasts.Manual.LangSerNumberInfo, new RecordItemIndex(6));
            LanguageSeries = repo.Laracasts.Manual.LangSerNumber.Element.GetAttributeValueText("Title");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", LanguageSeries, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Title' from item 'Laracasts.Manual.LangVidNumber' and assigning its value to variable 'LanguagesVideos'.", repo.Laracasts.Manual.LangVidNumberInfo, new RecordItemIndex(8));
            LanguagesVideos = repo.Laracasts.Manual.LangVidNumber.Element.GetAttributeValueText("Title");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", LanguagesVideos, new RecordItemIndex(9));
            
            // Techniques
            Report.Log(ReportLevel.Info, "Section", "Techniques", new RecordItemIndex(10));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Title' from item 'Laracasts.Manual.TechSerNumber' and assigning its value to variable 'TechniquesSeries'.", repo.Laracasts.Manual.TechSerNumberInfo, new RecordItemIndex(11));
            TechniquesSeries = repo.Laracasts.Manual.TechSerNumber.Element.GetAttributeValueText("Title");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", TechniquesSeries, new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'Title' from item 'Laracasts.Manual.TechVidNumber' and assigning its value to variable 'TechniquesVideos'.", repo.Laracasts.Manual.TechVidNumberInfo, new RecordItemIndex(13));
            TechniquesVideos = repo.Laracasts.Manual.TechVidNumber.Element.GetAttributeValueText("Title");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "User", TechniquesVideos, new RecordItemIndex(14));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
