///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Bakalarka.Vue.Laracasts
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Laracasts_close_singIn recording.
    /// </summary>
    [TestModule("f6094fd5-aa5a-4ba7-b184-06d725d3710e", ModuleType.Recording, 1)]
    public partial class Laracasts_close_singIn : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Bakalarka.BakalarkaRepository repository.
        /// </summary>
        public static global::Bakalarka.BakalarkaRepository repo = global::Bakalarka.BakalarkaRepository.Instance;

        static Laracasts_close_singIn instance = new Laracasts_close_singIn();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Laracasts_close_singIn()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Laracasts_close_singIn Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'Laracasts.SomeDivTag.MdTwPx4MdTwPy3TwAbsoluteTwBg'.", repo.Laracasts.SomeDivTag.MdTwPx4MdTwPy3TwAbsoluteTwBgInfo, new RecordItemIndex(0));
            repo.Laracasts.SomeDivTag.MdTwPx4MdTwPy3TwAbsoluteTwBg.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Laracasts.SomeDivTag.MdTwPx4MdTwPy3TwAbsoluteTwBg' at 47;18.", repo.Laracasts.SomeDivTag.MdTwPx4MdTwPy3TwAbsoluteTwBgInfo, new RecordItemIndex(1));
            repo.Laracasts.SomeDivTag.MdTwPx4MdTwPy3TwAbsoluteTwBg.MoveTo("47;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Laracasts.SomeDivTag.MdTwPx4MdTwPy3TwAbsoluteTwBg' at 47;18.", repo.Laracasts.SomeDivTag.MdTwPx4MdTwPy3TwAbsoluteTwBgInfo, new RecordItemIndex(2));
            repo.Laracasts.SomeDivTag.MdTwPx4MdTwPy3TwAbsoluteTwBg.Click("47;18");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
