///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Bakalarka.Vue.Laracasts
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Laracasts_goto_buildAClienCourse recording.
    /// </summary>
    [TestModule("8c689d44-cbb9-4dd5-8cbf-f4301279f369", ModuleType.Recording, 1)]
    public partial class Laracasts_goto_buildAClienCourse : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Bakalarka.BakalarkaRepository repository.
        /// </summary>
        public static global::Bakalarka.BakalarkaRepository repo = global::Bakalarka.BakalarkaRepository.Instance;

        static Laracasts_goto_buildAClienCourse instance = new Laracasts_goto_buildAClienCourse();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Laracasts_goto_buildAClienCourse()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Laracasts_goto_buildAClienCourse Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'Laracasts.Manual.BuildAClientCourse'.", repo.Laracasts.Manual.BuildAClientCourseInfo, new RecordItemIndex(0));
            repo.Laracasts.Manual.BuildAClientCourse.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Laracasts.Manual.BuildAClientCourse' at Center.", repo.Laracasts.Manual.BuildAClientCourseInfo, new RecordItemIndex(1));
            repo.Laracasts.Manual.BuildAClientCourse.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'Laracasts.SomeDivTag.LgTwFlexLgTwItemsCenter'.", repo.Laracasts.SomeDivTag.LgTwFlexLgTwItemsCenterInfo, new RecordItemIndex(2));
            repo.Laracasts.SomeDivTag.LgTwFlexLgTwItemsCenter.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeContains (Text>'laracasts.com/series/playing-with-php/episodes/2') on item 'PlayingWithPHPBuildAClientAppUsi.AdresniAVyhledavaciŘadek'.", repo.PlayingWithPHPBuildAClientAppUsi.AdresniAVyhledavaciŘadekInfo, new RecordItemIndex(3));
            Validate.AttributeContains(repo.PlayingWithPHPBuildAClientAppUsi.AdresniAVyhledavaciŘadekInfo, "Text", "laracasts.com/series/playing-with-php/episodes/2");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
