///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Bakalarka.Vue.Laracasts
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording_Laracasts recording.
    /// </summary>
    [TestModule("c9ee9acb-77a3-47be-932a-c4f1e75b87fa", ModuleType.Recording, 1)]
    public partial class Recording_Laracasts : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Bakalarka.BakalarkaRepository repository.
        /// </summary>
        public static global::Bakalarka.BakalarkaRepository repo = global::Bakalarka.BakalarkaRepository.Instance;

        static Recording_Laracasts instance = new Recording_Laracasts();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording_Laracasts()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording_Laracasts Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LaracastsGoogleChrome.ThomasShelbyPullMeFromTheDark' at 39;-19.", repo.LaracastsGoogleChrome.ThomasShelbyPullMeFromTheDarkInfo, new RecordItemIndex(0));
            repo.LaracastsGoogleChrome.ThomasShelbyPullMeFromTheDark.MoveTo("39;-19");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LaracastsGoogleChrome.AdresniAVyhledavaciŘadek' at 1375;136.", repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadekInfo, new RecordItemIndex(1));
            repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek.MoveTo("1375;136");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LaracastsGoogleChrome.AdresniAVyhledavaciŘadek' at 935;187.", repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadekInfo, new RecordItemIndex(2));
            repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek.MoveTo("935;187");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'vue' with focus on 'Laracasts'.", repo.Laracasts.SelfInfo, new RecordItemIndex(3));
            repo.Laracasts.Self.EnsureVisible();
            Keyboard.Press("vue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'Laracasts'.", repo.Laracasts.SelfInfo, new RecordItemIndex(4));
            repo.Laracasts.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LaracastsGoogleChrome.AdresniAVyhledavaciŘadek1' at 1455;124.", repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek1Info, new RecordItemIndex(5));
            repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek1.MoveTo("1455;124");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LaracastsGoogleChrome.AdresniAVyhledavaciŘadek1' at 1417;181.", repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek1Info, new RecordItemIndex(6));
            repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek1.MoveTo("1417;181");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LaracastsGoogleChrome.AdresniAVyhledavaciŘadek1' at -140;112.", repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek1Info, new RecordItemIndex(7));
            repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek1.MoveTo("-140;112");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LaracastsGoogleChrome.AdresniAVyhledavaciŘadek' at 1470;138.", repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadekInfo, new RecordItemIndex(8));
            repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek.MoveTo("1470;138");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LaracastsGoogleChrome.AdresniAVyhledavaciŘadek' at 1413;184.", repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadekInfo, new RecordItemIndex(9));
            repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek.MoveTo("1413;184");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LaracastsGoogleChrome.AdresniAVyhledavaciŘadek' at 1591;150.", repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadekInfo, new RecordItemIndex(10));
            repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek.MoveTo("1591;150");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LaracastsGoogleChrome.AdresniAVyhledavaciŘadek' at 1420;181.", repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadekInfo, new RecordItemIndex(11));
            repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek.MoveTo("1420;181");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -2040 units.", new RecordItemIndex(12));
            Mouse.ScrollWheel(-2040);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 840 units.", new RecordItemIndex(13));
            Mouse.ScrollWheel(840);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -600 units.", new RecordItemIndex(14));
            Mouse.ScrollWheel(-600);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LaracastsGoogleChrome.AdresniAVyhledavaciŘadek' at 1287;381.", repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadekInfo, new RecordItemIndex(15));
            repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek.MoveTo("1287;381");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'LaracastsGoogleChrome.AdresniAVyhledavaciŘadek2' at 1417;683.", repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek2Info, new RecordItemIndex(16));
            repo.LaracastsGoogleChrome.AdresniAVyhledavaciŘadek2.MoveTo("1417;683");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Laracasts.PauseIcon' at 56;7.", repo.Laracasts.PauseIconInfo, new RecordItemIndex(17));
            repo.Laracasts.PauseIcon.MoveTo("56;7");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Laracasts.PauseIcon' at -200;-46.", repo.Laracasts.PauseIconInfo, new RecordItemIndex(18));
            repo.Laracasts.PauseIcon.MoveTo("-200;-46");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -2400 units.", new RecordItemIndex(19));
            Mouse.ScrollWheel(-2400);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 1320 units.", new RecordItemIndex(20));
            Mouse.ScrollWheel(1320);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Laracasts.Explore' at 52;9.", repo.Laracasts.ExploreInfo, new RecordItemIndex(21));
            repo.Laracasts.Explore.MoveTo("52;9");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Laracasts.SomeDivTag.SomeSpanTag' at 870;537.", repo.Laracasts.SomeDivTag.SomeSpanTagInfo, new RecordItemIndex(22));
            repo.Laracasts.SomeDivTag.SomeSpanTag.Click("870;537");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -720 units.", new RecordItemIndex(23));
            Mouse.ScrollWheel(-720);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by 1440 units.", new RecordItemIndex(24));
            Mouse.ScrollWheel(1440);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Laracasts.LogoWhiteAnimated' at 33;19.", repo.Laracasts.LogoWhiteAnimatedInfo, new RecordItemIndex(25));
            repo.Laracasts.LogoWhiteAnimated.MoveTo("33;19");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Laracasts.SomeDivTag.WebElementSvg2' at 1588;64.", repo.Laracasts.SomeDivTag.WebElementSvg2Info, new RecordItemIndex(26));
            repo.Laracasts.SomeDivTag.WebElementSvg2.Click("1588;64");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Laracasts.SearchButton' at 354;15.", repo.Laracasts.SearchButtonInfo, new RecordItemIndex(27));
            repo.Laracasts.SearchButton.MoveTo("354;15");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{v up}ue' with focus on 'Laracasts.SearchButton'.", repo.Laracasts.SearchButtonInfo, new RecordItemIndex(28));
            repo.Laracasts.SearchButton.PressKeys("{v up}ue");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Laracasts.SearchButton' at 294;7.", repo.Laracasts.SearchButtonInfo, new RecordItemIndex(29));
            repo.Laracasts.SearchButton.MoveTo("294;7");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return up}' with focus on 'Laracasts'.", repo.Laracasts.SelfInfo, new RecordItemIndex(30));
            repo.Laracasts.Self.EnsureVisible();
            Keyboard.Press("{Return up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -360 units.", new RecordItemIndex(31));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Laracasts.SomeDivTag.SomeInputTag' at 354;599.", repo.Laracasts.SomeDivTag.SomeInputTagInfo, new RecordItemIndex(32));
            repo.Laracasts.SomeDivTag.SomeInputTag.MoveTo("354;599");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Laracasts.SomeDivTag.SomeInputTag' at 354;599.", repo.Laracasts.SomeDivTag.SomeInputTagInfo, new RecordItemIndex(33));
            repo.Laracasts.SomeDivTag.SomeInputTag.MoveTo("354;599");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Laracasts.SomeDivTag.ViewMore' at 68;14.", repo.Laracasts.SomeDivTag.ViewMoreInfo, new RecordItemIndex(34));
            repo.Laracasts.SomeDivTag.ViewMore.MoveTo("68;14");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Laracasts.SomeDivTag.BuildAClientAppUsing' at 126;13.", repo.Laracasts.SomeDivTag.BuildAClientAppUsingInfo, new RecordItemIndex(35));
            repo.Laracasts.SomeDivTag.BuildAClientAppUsing.MoveTo("126;13");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
