///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Bakalarka.Angular.Gmail
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Open_Gmail recording.
    /// </summary>
    [TestModule("9d894691-5de9-4480-af70-6da9813431ae", ModuleType.Recording, 1)]
    public partial class Open_Gmail : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Bakalarka.BakalarkaRepository repository.
        /// </summary>
        public static global::Bakalarka.BakalarkaRepository repo = global::Bakalarka.BakalarkaRepository.Instance;

        static Open_Gmail instance = new Open_Gmail();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Open_Gmail()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Open_Gmail Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            // Select email page
            Report.Log(ReportLevel.Info, "Section", "Select email page", new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'Gmail.IdentifierId'", repo.Gmail.IdentifierIdInfo, new ActionTimeout(5000), new RecordItemIndex(1));
            repo.Gmail.IdentifierIdInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Gmail.IdentifierId' at Center.", repo.Gmail.IdentifierIdInfo, new RecordItemIndex(2));
            repo.Gmail.IdentifierId.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to 'burdy8910@gmail.com' on item 'Gmail.IdentifierId'.", repo.Gmail.IdentifierIdInfo, new RecordItemIndex(3));
            repo.Gmail.IdentifierId.Element.SetAttributeValue("Value", "burdy8910@gmail.com");
            Delay.Milliseconds(0);
            
            // radsi pockat na vyplneni emailu
            Report.Log(ReportLevel.Info, "Delay", "radsi pockat na vyplneni emailu\r\nWaiting for 1s.", new RecordItemIndex(4));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Gmail.VfPpkdRLmnJb' at Center.", repo.Gmail.VfPpkdRLmnJbInfo, new RecordItemIndex(5));
            repo.Gmail.VfPpkdRLmnJb.Click();
            Delay.Milliseconds(0);
            
            // Fill password page
            Report.Log(ReportLevel.Info, "Section", "Fill password page", new RecordItemIndex(6));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'Gmail.Password'", repo.Gmail.PasswordInfo, new ActionTimeout(5000), new RecordItemIndex(7));
            repo.Gmail.PasswordInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Gmail.Password' at Center.", repo.Gmail.PasswordInfo, new RecordItemIndex(8));
            repo.Gmail.Password.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Value to 'ABC...123' on item 'Gmail.Password'.", repo.Gmail.PasswordInfo, new RecordItemIndex(9));
            repo.Gmail.Password.Element.SetAttributeValue("Value", "ABC...123");
            Delay.Milliseconds(0);
            
            // radsi pockat na vyplneni hesla
            Report.Log(ReportLevel.Info, "Delay", "radsi pockat na vyplneni hesla\r\nWaiting for 1s.", new RecordItemIndex(10));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Gmail.VfPpkdRLmnJb1' at Center.", repo.Gmail.VfPpkdRLmnJb1Info, new RecordItemIndex(11));
            repo.Gmail.VfPpkdRLmnJb1.Click();
            Delay.Milliseconds(0);
            
            // Logged in
            Report.Log(ReportLevel.Info, "Section", "Logged in", new RecordItemIndex(12));
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'DoručenaPošta134Burdy8910Atgmail1.AioUKr6le'.", repo.DoručenaPošta134Burdy8910Atgmail1.AioUKr6leInfo, new RecordItemIndex(13));
            repo.DoručenaPošta134Burdy8910Atgmail1.AioUKr6le.EnsureVisible();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "GmailLogedIn", null, false, new RecordItemIndex(14));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
