///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Bakalarka.React.Facebook
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The FB_login recording.
    /// </summary>
    [TestModule("ed68ddf0-d034-4647-bb7f-385167ecf9b0", ModuleType.Recording, 1)]
    public partial class FB_login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Bakalarka.BakalarkaRepository repository.
        /// </summary>
        public static global::Bakalarka.BakalarkaRepository repo = global::Bakalarka.BakalarkaRepository.Instance;

        static FB_login instance = new FB_login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public FB_login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static FB_login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Facebook.Manual._' at 839;179.", repo.Facebook.Manual._Info, new RecordItemIndex(0));
            repo.Facebook.Manual._.Click("839;179");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'FacebookPřihlasteSeNeboSeZaregist'.", repo.FacebookPřihlasteSeNeboSeZaregist.SelfInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.FacebookPřihlasteSeNeboSeZaregist.Self);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}burdy{LShiftKey down}8910{LShiftKey up}{RMenu down}{LControlKey down}{Vkey}{RMenu up}{LControlKey up}gmail.com' with focus on 'FacebookPřihlasteSeNeboSeZaregist'.", repo.FacebookPřihlasteSeNeboSeZaregist.SelfInfo, new RecordItemIndex(2));
            repo.FacebookPřihlasteSeNeboSeZaregist.Self.EnsureVisible();
            Keyboard.Press("{Back}burdy{LShiftKey down}8910{LShiftKey up}{RMenu down}{LControlKey down}{Vkey}{RMenu up}{LControlKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'FacebookPřihlasteSeNeboSeZaregist'.", repo.FacebookPřihlasteSeNeboSeZaregist.SelfInfo, new RecordItemIndex(3));
            repo.FacebookPřihlasteSeNeboSeZaregist.Self.EnsureVisible();
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'FacebookPřihlasteSeNeboSeZaregist'.", repo.FacebookPřihlasteSeNeboSeZaregist.SelfInfo, new RecordItemIndex(4));
            Keyboard.PrepareFocus(repo.FacebookPřihlasteSeNeboSeZaregist.Self);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'FacebookPřihlasteSeNeboSeZaregist'.", repo.FacebookPřihlasteSeNeboSeZaregist.SelfInfo, new RecordItemIndex(5));
            repo.FacebookPřihlasteSeNeboSeZaregist.Self.EnsureVisible();
            Keyboard.Press("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aaaa{LShiftKey down}1234{LShiftKey up}{Return}' with focus on 'FacebookPřihlasteSeNeboSeZaregist'.", repo.FacebookPřihlasteSeNeboSeZaregist.SelfInfo, new RecordItemIndex(6));
            repo.FacebookPřihlasteSeNeboSeZaregist.Self.EnsureVisible();
            Keyboard.Press("aaaa{LShiftKey down}1234{LShiftKey up}{Return}");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
