///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Bakalarka.React.myapp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The myapp_to_emojiPage_by_dropdown recording.
    /// </summary>
    [TestModule("236aa0aa-f40c-4e8c-b61d-91879bceda3a", ModuleType.Recording, 1)]
    public partial class Myapp_to_emojiPage_by_dropdown : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Bakalarka.BakalarkaRepository repository.
        /// </summary>
        public static global::Bakalarka.BakalarkaRepository repo = global::Bakalarka.BakalarkaRepository.Instance;

        static Myapp_to_emojiPage_by_dropdown instance = new Myapp_to_emojiPage_by_dropdown();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Myapp_to_emojiPage_by_dropdown()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Myapp_to_emojiPage_by_dropdown Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable navbarDropdown.
        /// </summary>
        [TestVariable("4f2a6af9-4918-4347-a681-5b01db437e28")]
        public string navbarDropdown
        {
            get { return repo.navbarDropdown; }
            set { repo.navbarDropdown = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ReactApp.Root.MiniApps' at Center.", repo.ReactApp.Root.MiniAppsInfo, new RecordItemIndex(0));
            repo.ReactApp.Root.MiniApps.MoveTo();
            Delay.Milliseconds(0);
            
            // Zdurazneni toho, ze v Ranorex se k tomuto prvku lze dostat (v RobotFW, ani webdriverIO ne)
            Report.Log(ReportLevel.Info, "Mouse", "Zdurazneni toho, ze v Ranorex se k tomuto prvku lze dostat (v RobotFW, ani webdriverIO ne)\r\nMouse Left Move item 'ReactApp.Root.EmojiPageDropdown' at Center.", repo.ReactApp.Root.EmojiPageDropdownInfo, new RecordItemIndex(1));
            repo.ReactApp.Root.EmojiPageDropdown.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "RedirectEmojiByNavbar", null, false, new RecordItemIndex(2));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ReactApp.Root.EmojiPageDropdown' at Center.", repo.ReactApp.Root.EmojiPageDropdownInfo, new RecordItemIndex(3));
            repo.ReactApp.Root.EmojiPageDropdown.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
