///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Bakalarka.React.myapp
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The myapp_Get_text_of_the_main_paragraph recording.
    /// </summary>
    [TestModule("a03a3ae2-a2b6-4960-8d6e-d0645508b661", ModuleType.Recording, 1)]
    public partial class Myapp_Get_text_of_the_main_paragraph : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Bakalarka.BakalarkaRepository repository.
        /// </summary>
        public static global::Bakalarka.BakalarkaRepository repo = global::Bakalarka.BakalarkaRepository.Instance;

        static Myapp_Get_text_of_the_main_paragraph instance = new Myapp_Get_text_of_the_main_paragraph();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Myapp_Get_text_of_the_main_paragraph()
        {
            MainParHeader = "";
            MainParText = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Myapp_Get_text_of_the_main_paragraph Instance
        {
            get { return instance; }
        }

#region Variables

        string _MainParHeader;

        /// <summary>
        /// Gets or sets the value of variable MainParHeader.
        /// </summary>
        [TestVariable("e9f4d748-d521-4bdf-b67d-73b3ff3ead5e")]
        public string MainParHeader
        {
            get { return _MainParHeader; }
            set { _MainParHeader = value; }
        }

        string _MainParText;

        /// <summary>
        /// Gets or sets the value of variable MainParText.
        /// </summary>
        [TestVariable("a92f69ff-9f06-4f70-b8c5-597db8e9eca4")]
        public string MainParText
        {
            get { return _MainParText; }
            set { _MainParText = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ReactApp.Root.H1TagNHL' and assigning its value to variable 'MainParHeader'.", repo.ReactApp.Root.H1TagNHLInfo, new RecordItemIndex(0));
            MainParHeader = repo.ReactApp.Root.H1TagNHL.Element.GetAttributeValueText("InnerText");
            
            Report.Log(ReportLevel.Info, "User", MainParHeader, new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Get Value", "Getting attribute 'InnerText' from item 'ReactApp.Root.TheNationalHockeyLeagueNHLFrench' and assigning its value to variable 'MainParText'.", repo.ReactApp.Root.TheNationalHockeyLeagueNHLFrenchInfo, new RecordItemIndex(2));
            MainParText = repo.ReactApp.Root.TheNationalHockeyLeagueNHLFrench.Element.GetAttributeValueText("InnerText");
            
            Report.Log(ReportLevel.Info, "User", MainParText, new RecordItemIndex(3));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
