///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Bakalarka.Angular.Prezman
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Prezman_redirect_to_item recording.
    /// </summary>
    [TestModule("b68955a6-6460-4dd2-bdfc-ce2920675099", ModuleType.Recording, 1)]
    public partial class Prezman_redirect_to_item : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Bakalarka.BakalarkaRepository repository.
        /// </summary>
        public static global::Bakalarka.BakalarkaRepository repo = global::Bakalarka.BakalarkaRepository.Instance;

        static Prezman_redirect_to_item instance = new Prezman_redirect_to_item();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Prezman_redirect_to_item()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Prezman_redirect_to_item Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Prezman.SliderButtonSliderButtonNext' at 51;79.", repo.Prezman.SliderButtonSliderButtonNextInfo, new RecordItemIndex(0));
            repo.Prezman.SliderButtonSliderButtonNext.MoveTo("51;79");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Prezman.SliderButtonSliderButtonNext' at 51;79.", repo.Prezman.SliderButtonSliderButtonNextInfo, new RecordItemIndex(1));
            repo.Prezman.SliderButtonSliderButtonNext.Click("51;79");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Prezman.SliderButtonSliderButtonNext' at 51;79.", repo.Prezman.SliderButtonSliderButtonNextInfo, new RecordItemIndex(2));
            repo.Prezman.SliderButtonSliderButtonNext.MoveTo("51;79");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Prezman.SliderButtonSliderButtonNext' at 51;79.", repo.Prezman.SliderButtonSliderButtonNextInfo, new RecordItemIndex(3));
            repo.Prezman.SliderButtonSliderButtonNext.Click("51;79");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Prezman.Realisations1' at 267;45.", repo.Prezman.Realisations1Info, new RecordItemIndex(4));
            repo.Prezman.Realisations1.Click("267;45");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Prezman.Manual.CarouselThirdItem' at 51;79.", repo.Prezman.Manual.CarouselThirdItemInfo, new RecordItemIndex(5));
            repo.Prezman.Manual.CarouselThirdItem.MoveTo("51;79");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Prezman.Manual.CarouselThirdItem' at 51;79.", repo.Prezman.Manual.CarouselThirdItemInfo, new RecordItemIndex(6));
            repo.Prezman.Manual.CarouselThirdItem.Click("51;79");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking EnsureVisible() on item 'Prezman.Manual.Video'.", repo.Prezman.Manual.VideoInfo, new RecordItemIndex(7));
            repo.Prezman.Manual.Video.EnsureVisible();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
