///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Bakalarka.Angular.Prezman
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Prezman_screenshot_duringHover_navbar recording.
    /// </summary>
    [TestModule("5aa9d35e-fda8-4665-a4f7-86a90ea5fb06", ModuleType.Recording, 1)]
    public partial class Prezman_screenshot_duringHover_navbar : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Bakalarka.BakalarkaRepository repository.
        /// </summary>
        public static global::Bakalarka.BakalarkaRepository repo = global::Bakalarka.BakalarkaRepository.Instance;

        static Prezman_screenshot_duringHover_navbar instance = new Prezman_screenshot_duringHover_navbar();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Prezman_screenshot_duringHover_navbar()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Prezman_screenshot_duringHover_navbar Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Prezman.Manual.NavbarRelations' at Center.", repo.Prezman.Manual.NavbarRelationsInfo, new RecordItemIndex(0));
            repo.Prezman.Manual.NavbarRelations.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "HoverRelations", null, false, new RecordItemIndex(1));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Prezman.Manual.NavbarAgence' at Center.", repo.Prezman.Manual.NavbarAgenceInfo, new RecordItemIndex(2));
            repo.Prezman.Manual.NavbarAgence.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "HoverAgence", null, false, new RecordItemIndex(3));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Prezman.Manual.NavbarOffers' at Center.", repo.Prezman.Manual.NavbarOffersInfo, new RecordItemIndex(4));
            repo.Prezman.Manual.NavbarOffers.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "HoverOffers", null, false, new RecordItemIndex(5));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Prezman.Manual.NavbarPlus' at Center.", repo.Prezman.Manual.NavbarPlusInfo, new RecordItemIndex(6));
            repo.Prezman.Manual.NavbarPlus.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "HoverPlus", null, false, new RecordItemIndex(7));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'Prezman.Manual.NavbarReferences' at Center.", repo.Prezman.Manual.NavbarReferencesInfo, new RecordItemIndex(8));
            repo.Prezman.Manual.NavbarReferences.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Screenshot(ReportLevel.Info, "User", "HoverReferences", null, false, new RecordItemIndex(9));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
