///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Bakalarka.Angular.Prezman
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording_Prezman recording.
    /// </summary>
    [TestModule("49828835-6e63-42e5-a136-50f1db7f6b08", ModuleType.Recording, 1)]
    public partial class Recording_Prezman : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Bakalarka.BakalarkaRepository repository.
        /// </summary>
        public static global::Bakalarka.BakalarkaRepository repo = global::Bakalarka.BakalarkaRepository.Instance;

        static Recording_Prezman instance = new Recording_Prezman();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording_Prezman()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording_Prezman Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.WebElementSvg' at 85;5.", repo.Prezman.WebElementSvgInfo, new RecordItemIndex(0));
            repo.Prezman.WebElementSvg.MoveTo("85;5");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.WebElementSvg' at 754;13.", repo.Prezman.WebElementSvgInfo, new RecordItemIndex(1));
            repo.Prezman.WebElementSvg.MoveTo("754;13");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.WebElementSvg' at 884;7.", repo.Prezman.WebElementSvgInfo, new RecordItemIndex(2));
            repo.Prezman.WebElementSvg.MoveTo("884;7");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.WebElementSvg' at 949;3.", repo.Prezman.WebElementSvgInfo, new RecordItemIndex(3));
            repo.Prezman.WebElementSvg.MoveTo("949;3");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.WebElementSvg' at 1033;4.", repo.Prezman.WebElementSvgInfo, new RecordItemIndex(4));
            repo.Prezman.WebElementSvg.MoveTo("1033;4");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.WebElementSvg' at 1130;5.", repo.Prezman.WebElementSvgInfo, new RecordItemIndex(5));
            repo.Prezman.WebElementSvg.MoveTo("1130;5");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.VignetteUseCase' at 106;80.", repo.Prezman.VignetteUseCaseInfo, new RecordItemIndex(6));
            repo.Prezman.VignetteUseCase.MoveTo("106;80");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.SomeImgTag' at 1182;350.", repo.Prezman.SomeImgTagInfo, new RecordItemIndex(7));
            repo.Prezman.SomeImgTag.MoveTo("1182;350");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.SomeImgTag' at 1096;419.", repo.Prezman.SomeImgTagInfo, new RecordItemIndex(8));
            repo.Prezman.SomeImgTag.MoveTo("1096;419");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.SomeImgTag' at 990;46.", repo.Prezman.SomeImgTagInfo, new RecordItemIndex(9));
            repo.Prezman.SomeImgTag.MoveTo("990;46");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.SomeImgTag' at 1076;44.", repo.Prezman.SomeImgTagInfo, new RecordItemIndex(10));
            repo.Prezman.SomeImgTag.MoveTo("1076;44");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.SomeImgTag' at 1153;48.", repo.Prezman.SomeImgTagInfo, new RecordItemIndex(11));
            repo.Prezman.SomeImgTag.MoveTo("1153;48");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.SomeImgTag' at 1263;48.", repo.Prezman.SomeImgTagInfo, new RecordItemIndex(12));
            repo.Prezman.SomeImgTag.MoveTo("1263;48");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.SomeImgTag' at 1254;46.", repo.Prezman.SomeImgTagInfo, new RecordItemIndex(13));
            repo.Prezman.SomeImgTag.MoveTo("1254;46");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Prezman.SomeImgTag' at 169;40.", repo.Prezman.SomeImgTagInfo, new RecordItemIndex(14));
            repo.Prezman.SomeImgTag.MoveTo("169;40");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
