///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Bakalarka.Vue.GitLab
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Gitlab_OpenBrowser recording.
    /// </summary>
    [TestModule("aa27309e-2408-4f4e-8496-0e5dabfb8083", ModuleType.Recording, 1)]
    public partial class Gitlab_OpenBrowser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::Bakalarka.BakalarkaRepository repository.
        /// </summary>
        public static global::Bakalarka.BakalarkaRepository repo = global::Bakalarka.BakalarkaRepository.Instance;

        static Gitlab_OpenBrowser instance = new Gitlab_OpenBrowser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Gitlab_OpenBrowser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Gitlab_OpenBrowser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'https://about.gitlab.com/' with browser 'Chrome' in maximized mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("https://about.gitlab.com/", "Chrome", "", false, true, false, false, false, true);
            Delay.Milliseconds(0);
            
            // Private mode
            //OpenBrowserPrivate("https://about.gitlab.com/", "Chrome");
            //Delay.Milliseconds(0);
            
            // V private mode nelokalizuje
            //Report.Log(ReportLevel.Info, "Mouse", "V private mode nelokalizuje\r\nMouse Left Click item 'IterateFasterInnovateTogetherGitL.ATagSignIn' at Center.", repo.IterateFasterInnovateTogetherGitL.ATagSignInInfo, new RecordItemIndex(2));
            //repo.IterateFasterInnovateTogetherGitL.ATagSignIn.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'IterateFasterInnovateTogetherGitL.NavbarSignIn' at Center.", repo.IterateFasterInnovateTogetherGitL.NavbarSignInInfo, new RecordItemIndex(3));
            repo.IterateFasterInnovateTogetherGitL.NavbarSignIn.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'SignInGitLab.Commit'", repo.SignInGitLab.CommitInfo, new ActionTimeout(30000), new RecordItemIndex(4));
            repo.SignInGitLab.CommitInfo.WaitForExists(30000);
            
            Report.Screenshot(ReportLevel.Info, "User", "GitlabSignIn", null, false, new RecordItemIndex(5));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
